"""LLM Wiki 生成器 — 将搜索结果组织为结构化知识Wiki."""

import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class WikiGenerator:
    """LLM驱动的结构化Wiki页面生成。

    流程:
    1. 输入论文列表（含LLM摘要+期刊等级）
    2. LLM聚类分组（2-4个主题）
    3. 生成 index.md + 各主题子页面
    4. 生成 metadata.json + survey.md
    """

    def __init__(self, llm_client):
        self.llm = llm_client

    # ── Wiki 生成 ────────────────────────────────────────

    WIKI_STRUCTURE_PROMPT = """你是一个学术知识组织专家。给定一批论文及其摘要，
请将它们按研究方向分组，并生成结构化Wiki的目录大纲。

输出纯 JSON:
{
  "topics": [
    {
      "title": "研究方向名称",
      "description": "一句话描述这个方向",
      "paper_ids": ["paper_id_1", "paper_id_2"]
    }
  ],
  "cross_cutting": "跨领域观察（一句话）"
}

分组原则:
- 2-5个组，每组3-20篇
- 每篇论文只归入最主要的一个组
- 顶级会议/期刊(A+级)的论文在描述中标注⭐"""

    async def generate_structure(self, papers: list[dict]) -> dict:
        """LLM生成Wiki目录结构。"""
        paper_list = []
        for p in papers[:100]:
            paper_list.append(
                f"ID:{p.get('paper_id','?')[:10]} | "
                f"Title:{p.get('title','')[:80]} | "
                f"Level:{p.get('level','?')} | "
                f"Digest:{p.get('digest','')[:100]}"
            )
        user_msg = "\n".join(paper_list)
        try:
            return await self.llm._chat_json(self.WIKI_STRUCTURE_PROMPT, user_msg)
        except Exception as e:
            logger.warning(f"Wiki结构生成失败: {e}")
            return {"topics": [{"title": "All Papers", "description": "", "paper_ids": [p.get('paper_id','') for p in papers]}]}

    async def generate_index(self, structure: dict, project_query: str) -> str:
        """生成Wiki首页 index.md。"""
        topics_md = ""
        for i, t in enumerate(structure.get("topics", []), 1):
            count = len(t.get("paper_ids", []))
            topics_md += f"{i}. **[{t['title']}]({self._slug(t['title'])}.md)** ({count} papers)\n"
            topics_md += f"   {t.get('description', '')}\n\n"

        return f"""# Literature Review: {project_query}

> Auto-generated by ZhiYu Research Agent

## Research Directions

{topics_md}

## Cross-cutting Observation

{structure.get('cross_cutting', '')}

## Quick Stats

- Total papers: {sum(len(t.get('paper_ids',[])) for t in structure.get('topics',[]))}
- Research directions: {len(structure.get('topics',[]))}
"""

    async def generate_topic_page(self, topic: dict, papers: list[dict]) -> str:
        """生成单个主题的Wiki页面。"""
        title = topic.get("title", "Untitled")
        desc = topic.get("description", "")

        papers_md = ""
        aplus_count = 0
        for p in papers:
            level = p.get("level", "")
            star = " ⭐" if level == "A+" else ""
            if star:
                aplus_count += 1
            authors = p.get("authors", [])
            if isinstance(authors, str):
                try:
                    authors = json.loads(authors)
                except Exception:
                    authors = [authors]
            first_author = authors[0] if authors else "?"
            year = p.get("year", "?")

            papers_md += f"""### {p.get('title', 'Untitled')}{star}

- **Authors**: {', '.join(authors[:5])}
- **Year**: {year} | **Source**: {p.get('source', '?')} | **Level**: {level or 'N/A'}
- **DOI**: {p.get('doi', '')}
- **One-liner**: {p.get('one_liner', '')}
- **Key Points**:
"""
            digest = p.get("digest", [])
            if isinstance(digest, str):
                digest = [digest]
            for d in digest[:5]:
                papers_md += f"  - {d}\n"
            papers_md += "\n"

        return f"""# {title}

> {desc} | {len(papers)} papers | {aplus_count} top-tier ⭐

{papers_md}
"""

    def _slug(self, title: str) -> str:
        return title.lower().replace(" ", "_").replace("/", "-")[:40]

    async def generate_wiki(
        self, papers: list[dict], project_id: str, output_dir: Path, user_query: str = ""
    ) -> Path:
        """生成完整Wiki。

        Args:
            papers: 论文列表，每篇包含 paper_id, title, authors, year, source,
                    level, one_liner, digest, doi, venue
            project_id: 项目ID
            output_dir: 输出根目录（在下面创建 wiki/ 子目录）
            user_query: 原始搜索意图

        Returns:
            Wiki index.md 的路径
        """
        wiki_dir = output_dir / "wiki"
        wiki_dir.mkdir(parents=True, exist_ok=True)

        # 1. LLM生成目录结构
        structure = await self.generate_structure(papers)

        # 2. 构建 paper_id → paper 映射
        paper_map = {p.get("paper_id", ""): p for p in papers}

        # 3. 生成index.md
        index_md = await self.generate_index(structure, user_query)
        (wiki_dir / "index.md").write_text(index_md, encoding="utf-8")

        # 4. 生成各主题页面
        for topic in structure.get("topics", []):
            topic_papers = [paper_map.get(pid) for pid in topic.get("paper_ids", [])]
            topic_papers = [p for p in topic_papers if p is not None]
            if not topic_papers:
                continue
            page_md = await self.generate_topic_page(topic, topic_papers)
            slug = self._slug(topic["title"])
            (wiki_dir / f"{slug}.md").write_text(page_md, encoding="utf-8")

        logger.info(f"Wiki: {len(structure.get('topics',[]))} topics → {wiki_dir}")
        return wiki_dir / "index.md"

    # ── JSON 元数据导出 ──────────────────────────────────

    async def export_metadata_json(self, papers: list[dict], output_path: Path):
        """导出结构化JSON元数据文件。"""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # 按等级分组
        by_level = {"A+": [], "A": [], "B": [], "C": [], "unranked": []}
        for p in papers:
            level = p.get("level") or "unranked"
            if level not in by_level:
                level = "unranked"
            by_level[level].append({
                "title": p.get("title"),
                "authors": p.get("authors") if isinstance(p.get("authors"), list) else json.loads(p.get("authors", "[]")),
                "year": p.get("year"),
                "doi": p.get("doi"),
                "source": p.get("source"),
                "venue": p.get("venue"),
                "level": level,
                "citations": p.get("citation_count"),
                "one_liner": p.get("one_liner"),
                "digest": p.get("digest"),
                "method_tags": p.get("method_tags"),
                "dataset": p.get("dataset_info"),
                "reading_level": p.get("reading_level"),
            })

        output = {
            "total": len(papers),
            "by_level": {k: len(v) for k, v in by_level.items()},
            "papers": by_level,
        }
        output_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
        logger.info(f"JSON metadata: {output_path}")
